/**
 * Turn a SchoolDef into a complete on-disk fixture.
 *
 * Pure: takes a definition, returns the fixture's JSON payload. The CLI in
 * tools/ingest does the file writing, keeping I/O out of this package.
 */

import { lonLatToUtm, ringAreaM2, utmZoneFor } from '@canopy/core';
import type { SchoolDef } from './schools.js';
import { generateScene, L9_B10, type SceneOut } from './scene.js';
import { deriveRecessYard } from './recessYard.js';

/** Extent of the analysis window, in metres. 2 km serves the neighbourhood fit. */
export const EXTENT_M = 2000;
export const FINE_PIXEL_M = 10;
export const THERMAL_PIXEL_M = 100;

export interface FixturePayload {
  readonly meta: Record<string, unknown>;
  readonly scene: SceneOut;
  /** Yard ring in projected metres. */
  readonly yardUtm: ReadonlyArray<readonly [number, number]>;
}

/** Even–odd point-in-ring, duplicated locally to keep this package dependency-light. */
function inRing(ring: ReadonlyArray<readonly [number, number]>, x: number, y: number): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]!;
    const [xj, yj] = ring[j]!;
    if (yi > y !== yj > y) {
      const t = (y - yi) / (yj - yi);
      if (x < xi + t * (xj - xi)) inside = !inside;
    }
  }
  return inside;
}

/**
 * Build the fixture for one school.
 *
 * The grid is centred on the yard's centroid and snapped to a 100 m boundary so
 * the fine and thermal grids share an origin exactly — otherwise the
 * area-weighted resample would carry a half-pixel bias into every regression.
 */
export function buildFixture(def: SchoolDef): FixturePayload {
  const lons = def.ringWgs84.map((p) => p[0]);
  const lats = def.ringWgs84.map((p) => p[1]);
  const cLon = (Math.min(...lons) + Math.max(...lons)) / 2;
  const cLat = (Math.min(...lats) + Math.max(...lats)) / 2;

  const zone = utmZoneFor(cLon, cLat);
  const parcelUtm = def.ringWgs84.map((p) => lonLatToUtm(p[0], p[1], zone));
  // The plan is about the recess yard, not the whole parcel. See recessYard.ts.
  const yard = deriveRecessYard(parcelUtm);
  const yardUtm = yard.ring;
  const [cx, cy] = lonLatToUtm(cLon, cLat, zone);

  // Snap the origin to the thermal grid so both rasters align on a 100 m lattice.
  const originX = Math.floor((cx - EXTENT_M / 2) / THERMAL_PIXEL_M) * THERMAL_PIXEL_M;
  const originY = Math.ceil((cy + EXTENT_M / 2) / THERMAL_PIXEL_M) * THERMAL_PIXEL_M;

  const fineSize = EXTENT_M / FINE_PIXEL_M;
  const thermalSize = EXTENT_M / THERMAL_PIXEL_M;

  const scene = generateScene(
    {
      slug: def.slug,
      seed: def.seed,
      fineSize,
      thermalSize,
      originX,
      originY,
      epsg: zone.epsg,
      ndviMean: def.ndviMean,
      ndviSpread: def.ndviSpread,
      yardCanopyTarget: def.yardCanopyTarget,
      lstIntercept: def.lstIntercept,
      lstSlope: def.lstSlope,
      targetR2: def.targetR2,
      cloudFraction: def.cloudFraction,
    },
    (x, y) => inRing(yardUtm, x, y),
  );

  const yardAreaM2 = yard.areaM2;

  const meta = {
    slug: def.slug,
    name: def.name,
    city: def.city,
    state: def.state,
    synthetic: true,
    provenance:
      `Parcel polygon: OpenStreetMap way ${def.osmWayId} (ODbL), retrieved 2026-08-05. ` +
      `${yard.method} ` +
      `Pixel values: SYNTHETIC, generated by @canopy/fixtures-synth seed ${def.seed}. ` +
      `See docs/DATA.md for the real-imagery swap procedure.`,
    osmWayId: def.osmWayId,
    yardAreaM2,
    parcelAreaM2: yard.parcelAreaM2,
    yardDerivation: yard.method,
    ndviCanopyThreshold: def.ndviCanopyThreshold,
    thresholdRationale: def.thresholdRationale,
    opticalSceneId: `SYNTH_S2_${def.slug.toUpperCase().replace(/-/g, '_')}`,
    opticalDate: def.opticalDate,
    note: def.note,
    grid: {
      epsg: zone.epsg,
      originX,
      originY,
      finePixelM: FINE_PIXEL_M,
      thermalPixelM: THERMAL_PIXEL_M,
      fineSize,
      thermalSize,
    },
    mtl: {
      radianceMult: L9_B10.radianceMult,
      radianceAdd: L9_B10.radianceAdd,
      k1: L9_B10.k1,
      k2: L9_B10.k2,
      spacecraft: 'LANDSAT_9',
      acquisitionDate: def.acquisitionDate,
      localOverpassTime: def.localOverpassTime,
      sceneId: `SYNTH_LC09_${def.slug.toUpperCase().replace(/-/g, '_')}`,
    },
    groundTruth: scene.groundTruth,
  };

  return { meta, scene, yardUtm };
}
