/**
 * The four fixture schools.
 *
 * REAL: school names, OpenStreetMap way IDs, and yard polygons — genuine OSM
 * geometry, retrieved 2026-08-05, licensed ODbL.
 * SYNTHETIC: the pixel values, generated by scene.ts with a fixed seed.
 *
 * Slot design follows the four cases the product must handle, so the demo can
 * show generalisation rather than one lucky school:
 *
 *   1 cactus-wren  hot + low canopy .... the hero. Biggest defensible ΔT.
 *   2 john-jacobs  moderate canopy ...... shows the tool generalises.
 *   3 sunridge     already well shaded .. Canopy recommends little. Proof it is
 *                                        a measurement tool, not a tree seller.
 *   4 dos-rios     cloud contaminated ... the on-camera refusal.
 */

export interface SchoolDef {
  readonly slug: string;
  readonly name: string;
  readonly city: string;
  readonly state: string;
  /** OpenStreetMap way id — the polygon's provenance. */
  readonly osmWayId: number;
  /** Real OSM ring, WGS84 [lon, lat], not closed. */
  readonly ringWgs84: ReadonlyArray<readonly [number, number]>;
  /** Per-site NDVI canopy threshold, and why. */
  readonly ndviCanopyThreshold: number;
  readonly thresholdRationale: string;
  readonly seed: number;
  /** Scene character — see SceneSpec. */
  readonly ndviMean: number;
  readonly ndviSpread: number;
  readonly yardCanopyTarget: number;
  readonly lstIntercept: number;
  readonly lstSlope: number;
  /** Declared fit quality. Below 0.30 the ΔT must suppress. */
  readonly targetR2: number;
  readonly cloudFraction: number;
  readonly acquisitionDate: string;
  readonly localOverpassTime: string;
  readonly opticalDate: string;
  readonly note: string;
}

const ARID_THRESHOLD_RATIONALE =
  'Raised above the 0.60 default: in irrigated desert turf, well-watered grass ' +
  'can exceed 0.60 and would be miscounted as tree canopy. Hand-validated ' +
  'against visible imagery for this yard.';

export const SCHOOLS: readonly SchoolDef[] = [
  {
    slug: "cactus-wren",
    name: "Cactus Wren Elementary School",
    city: 'Phoenix',
    state: 'AZ',
    osmWayId: 121203200,
    ringWgs84: [
      [-112.1451758, 33.5754404],
      [-112.1447386, 33.5758628],
      [-112.1446957, 33.5758673],
      [-112.1434435, 33.5749754],
      [-112.1431124, 33.5747343],
      [-112.142946, 33.5747335],
      [-112.1429612, 33.5730766],
      [-112.1429619, 33.5730008],
      [-112.1429798, 33.572966],
      [-112.1430162, 33.5729424],
      [-112.145209, 33.5729397],
    ],
    ndviCanopyThreshold: 0.66,
    thresholdRationale: ARID_THRESHOLD_RATIONALE,
    seed: 20260805,
    ndviMean: 0.14,
    ndviSpread: 0.09,
    yardCanopyTarget: 0.09,
    lstIntercept: 46.2,
    lstSlope: -15.4,
    targetR2: 0.72,
    cloudFraction: 0,
    acquisitionDate: '2025-07-29',
    localOverpassTime: '10:42',
    opticalDate: '2025-07-30',
    note: "Hero fixture: hot, low-canopy arid schoolyard. Largest defensible temperature effect.",
  },
  {
    slug: "john-jacobs",
    name: "John Jacobs Elementary School",
    city: 'Phoenix',
    state: 'AZ',
    osmWayId: 121870035,
    ringWgs84: [
      [-112.1078761, 33.6182962],
      [-112.1078756, 33.6164042],
      [-112.1100414, 33.6163747],
      [-112.110068, 33.6164567],
      [-112.1100206, 33.6165222],
      [-112.1100294, 33.616565],
      [-112.1100346, 33.6166975],
      [-112.1101075, 33.6167469],
      [-112.1103318, 33.6168781],
      [-112.1104135, 33.6169258],
      [-112.1103712, 33.6169817],
      [-112.1103062, 33.6170699],
      [-112.1102492, 33.6171548],
      [-112.1102016, 33.6172396],
      [-112.1101665, 33.6173169],
      [-112.1101386, 33.6173907],
      [-112.1100997, 33.6174976],
      [-112.1100701, 33.6176283],
      [-112.1100595, 33.6177166],
      [-112.1100536, 33.6178426],
      [-112.1100494, 33.6179494],
      [-112.1100474, 33.6181398],
      [-112.1100469, 33.6182056],
      [-112.1100465, 33.6182463],
      [-112.1099773, 33.6182475],
      [-112.108208, 33.6182785],
    ],
    ndviCanopyThreshold: 0.62,
    thresholdRationale: ARID_THRESHOLD_RATIONALE,
    seed: 20260806,
    ndviMean: 0.22,
    ndviSpread: 0.11,
    yardCanopyTarget: 0.24,
    lstIntercept: 44.1,
    lstSlope: -13.1,
    targetR2: 0.63,
    cloudFraction: 0,
    acquisitionDate: '2025-07-29',
    localOverpassTime: '10:42',
    opticalDate: '2025-07-30',
    note: "Moderate existing canopy: shows the tool generalises beyond the hero site.",
  },
  {
    slug: "sunridge",
    name: "Sunridge Elementary School",
    city: 'Phoenix',
    state: 'AZ',
    osmWayId: 66166058,
    ringWgs84: [
      [-112.192979, 33.4588394],
      [-112.1949656, 33.4588245],
      [-112.1950002, 33.4588272],
      [-112.1950252, 33.4588379],
      [-112.195055, 33.4588628],
      [-112.1950679, 33.4588809],
      [-112.1950751, 33.4589045],
      [-112.1950682, 33.4604061],
      [-112.1929811, 33.4604067],
      [-112.1929805, 33.4600015],
    ],
    ndviCanopyThreshold: 0.6,
    thresholdRationale: 'Standard 0.60 threshold: this yard has mature shade trees that separate cleanly from turf in visible imagery.',
    seed: 20260807,
    ndviMean: 0.33,
    ndviSpread: 0.13,
    yardCanopyTarget: 0.55,
    lstIntercept: 42,
    lstSlope: -11.8,
    targetR2: 0.55,
    cloudFraction: 0,
    acquisitionDate: '2025-07-29',
    localOverpassTime: '10:42',
    opticalDate: '2025-07-30',
    note: "Already well shaded: Canopy should recommend little or nothing here.",
  },
  {
    slug: "dos-rios",
    name: "Dos Rios Elementary School",
    city: 'Phoenix',
    state: 'AZ',
    osmWayId: 152752071,
    ringWgs84: [
      [-112.249116, 33.426975],
      [-112.2488717, 33.4267976],
      [-112.2488324, 33.4264777],
      [-112.247681, 33.4265869],
      [-112.2471583, 33.4265787],
      [-112.247137, 33.4265802],
      [-112.2471139, 33.426593],
      [-112.2470932, 33.4266173],
      [-112.2470875, 33.4266568],
      [-112.2470708, 33.4273254],
      [-112.2470389, 33.4291331],
      [-112.2470413, 33.4291567],
      [-112.2470505, 33.4291839],
      [-112.2470689, 33.4292019],
      [-112.2471002, 33.4292194],
      [-112.2471315, 33.4292283],
      [-112.247172, 33.4292293],
      [-112.2494063, 33.4290064],
    ],
    ndviCanopyThreshold: 0.63,
    thresholdRationale: ARID_THRESHOLD_RATIONALE,
    seed: 20260808,
    ndviMean: 0.16,
    ndviSpread: 0.1,
    yardCanopyTarget: 0.12,
    lstIntercept: 45.5,
    lstSlope: -14.6,
    targetR2: 0.68,
    cloudFraction: 0.34,
    acquisitionDate: '2025-07-29',
    localOverpassTime: '10:42',
    opticalDate: '2025-07-30',
    note: "Cloud-contaminated: the on-camera refusal. A third of the yard is masked.",
  },
];
